server:
  port: ${PORT:5000}

spring:
    boot:
      admin:
        client:
          instance:
            metadata:
              user:
                name: "admin"
                password: "pass"

management:
  security:
    enabled: false

eureka:
  server:
    response-cache-update-interval-ms: 3600000
    eviction-interval-timer-in-ms: 3600000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: "/actuator/health"
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    password: ${EUREKA_USER_PASSWORD:password}