server:
  port: ${PORT:5000}
  
security:
  user:
    password: ${eureka.password}

eureka:
  server:
    response-cache-update-interval-ms: 3600000
    eviction-interval-timer-in-ms: 3600000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    password: ${EUREKA_USER_PASSWORD:password}